-- JALANKAN SCRIPT INI DI SQL EDITOR SUPABASE

-- Reset Schema (Opsional: Hapus tabel lama jika ada agar bersih)
DROP TABLE IF EXISTS harga CASCADE;
DROP TABLE IF EXISTS ketersediaan CASCADE;
DROP TABLE IF EXISTS logs CASCADE;
DROP TABLE IF EXISTS pedagang CASCADE;
DROP TABLE IF EXISTS pasar CASCADE;
DROP TABLE IF EXISTS komoditas CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS settings CASCADE;

-- 1. Tabel Komoditas
CREATE TABLE komoditas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    satuan TEXT NOT NULL,
    kategori TEXT NOT NULL,
    harga_base INTEGER NOT NULL
);

-- 2. Tabel Pasar
CREATE TABLE pasar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    kode TEXT NOT NULL,
    alamat TEXT,
    jam_operasional TEXT,
    icon TEXT,
    pedagang_count INTEGER DEFAULT 0
);

-- 3. Tabel Pedagang
CREATE TABLE pedagang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    pasar_id BIGINT REFERENCES pasar(id) ON DELETE SET NULL,
    lapak TEXT,
    telp TEXT,
    komoditas_list TEXT,
    status TEXT DEFAULT 'aktif'
);

-- 4. Tabel Harga
CREATE TABLE harga (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    komoditas_id BIGINT REFERENCES komoditas(id) ON DELETE CASCADE,
    pasar_id BIGINT REFERENCES pasar(id) ON DELETE CASCADE,
    pedagang_id BIGINT REFERENCES pedagang(id) ON DELETE CASCADE,
    harga INTEGER NOT NULL,
    tanggal DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabel Users
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL,
    status TEXT DEFAULT 'aktif',
    last_login TEXT,
    pasar_ids TEXT
);

-- 6. Tabel Logs
CREATE TABLE logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    waktu TEXT,
    aksi TEXT,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    pasar_id BIGINT REFERENCES pasar(id) ON DELETE SET NULL
);

-- 7. Tabel Settings
CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- 8. Tabel Ketersediaan
CREATE TABLE ketersediaan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    komoditas_id BIGINT REFERENCES komoditas(id) ON DELETE CASCADE,
    pasar_id BIGINT REFERENCES pasar(id) ON DELETE CASCADE,
    ketersediaan INTEGER DEFAULT 100,
    status TEXT DEFAULT 'Tersedia',
    updated_at DATE DEFAULT CURRENT_DATE
);

-- --- SEED DATA (DATA AWAL) ---

-- Settings
INSERT INTO settings (key, value) VALUES 
('kadis_nama', 'Ir. Hj. ELY SUMINAR, M.P.'),
('kadis_jabatan', 'Kepala Dinas Ketahanan Pangan, Pertanian dan Perikanan Kota Tasikmalaya'),
('kadis_sambutan', 'Kami berkomitmen untuk terus menyajikan data harga komoditas yang akurat dan transparan bagi masyarakat. Portal ini hadir sebagai wujud transparansi pemerintah dalam menyediakan informasi harga yang dapat diandalkan.'),
('kadis_foto', 'https://dkp3.tasikmalayakota.go.id/');

-- Komoditas
INSERT INTO komoditas (nama, satuan, kategori, harga_base) VALUES
('Beras Medium', 'kg', 'Beras', 12500),
('Beras Premium', 'kg', 'Beras', 15000),
('Cabai Merah', 'kg', 'Sayuran', 45000),
('Cabai Rawit', 'kg', 'Sayuran', 58000),
('Bawang Merah', 'kg', 'Bumbu', 38000),
('Bawang Putih', 'kg', 'Bumbu', 32000),
('Minyak Goreng', 'liter', 'Minyak', 17000),
('Gula Pasir', 'kg', 'Gula', 14000),
('Tepung Terigu', 'kg', 'Bahan Pokok', 10500),
('Daging Sapi', 'kg', 'Daging', 130000),
('Daging Ayam', 'kg', 'Daging', 35000),
('Telur Ayam', 'kg', 'Telur', 28000),
('Ikan Kembung', 'kg', 'Ikan', 30000),
('Ikan Tongkol', 'kg', 'Ikan', 28000),
('Kedelai', 'kg', 'Kacang', 11000),
('Jagung', 'kg', 'Padi-padian', 8500),
('Tomat', 'kg', 'Sayuran', 12000),
('Kentang', 'kg', 'Sayuran', 15000);

-- Pasar
INSERT INTO pasar (nama, kode, alamat, jam_operasional, icon, pedagang_count) VALUES
('Pasar Tradisional A', 'A', 'Jl. Pahlawan No.1', '05.00–14.00', '🏪', 38),
('Pasar Induk B', 'B', 'Jl. Raya Industri No.12', '04.00–16.00', '🏬', 51),
('Pasar Satelit C', 'C', 'Jl. Merdeka No.5', '06.00–13.00', '🛒', 22),
('Pasar Modern D', 'D', 'Jl. Diponegoro No.88', '07.00–20.00', '🏢', 31),
('Pasar Rakyat E', 'E', 'Jl. Sudirman No.44', '05.30–14.30', '🛍️', 27);

-- Pedagang
INSERT INTO pedagang (nama, pasar_id, lapak, telp, komoditas_list) VALUES
('Ibu Sari Dewi', 1, 'A-001', '0812-3456-7890', 'Beras Medium, Beras Premium'),
('Pak Joni Prasetyo', 1, 'A-023', '0813-2345-6789', 'Cabai Merah, Cabai Rawit'),
('Bu Rohayati', 1, 'A-045', '0811-3456-7890', 'Minyak Goreng, Gula Pasir'),
('Pak Samsuri', 2, 'B-012', '0814-5678-9012', 'Daging Sapi, Daging Ayam'),
('Bu Aminah', 2, 'B-034', '0815-6789-0123', 'Tomat, Kentang, Sayuran'),
('Pak Hendra', 2, 'B-056', '0816-7890-1234', 'Ikan Kembung, Ikan Tongkol'),
('Bu Lastri', 3, 'C-001', '0817-8901-2345', 'Telur Ayam, Daging Ayam'),
('Pak Wahyu', 3, 'C-021', '0818-9012-3456', 'Tepung Terigu, Kedelai'),
('Bu Wati Susanti', 4, 'D-010', '0819-0123-4567', 'Beras, Minyak, Gula'),
('Pak Rudi Hartono', 5, 'E-003', '0820-1234-5678', 'Jagung, Kentang, Bawang');

-- Users (Password disesuaikan dengan README)
INSERT INTO users (nama, username, password, role, status, last_login, pasar_ids) VALUES
('Dr. Ahmad Supriadi', 'admin', 'admin123', 'admin', 'aktif', 'Hari ini 08:45', null),
('Ir. Budi Santoso, MM', 'dinas', 'dinas123', 'dinas', 'aktif', 'Hari ini 09:12', null),
('Citra Lestari', 'enum1', 'enum1', 'enumerator', 'aktif', 'Hari ini 10:05', '1,2'),
('Dedi Kurniawan', 'enum2', 'enum2', 'enumerator', 'aktif', 'Kemarin 16:30', '1,3'),
('Eka Putri', 'enum3', 'enum3', 'enumerator', 'aktif', 'Hari ini 09:50', '2,4'),
('Fauzan Hakim', 'enum4', 'enum4', 'enumerator', 'nonaktif', '3 hari lalu', '3,5'),
('Gina Permata', 'enum5', 'enum5', 'enumerator', 'aktif', 'Hari ini 10:18', '4,5');

-- Logs
INSERT INTO logs (waktu, aksi, user_id, pasar_id) VALUES
('10:32', 'Input harga Beras Medium', 3, 1),
('10:28', 'Input harga Cabai Rawit', 5, 3),
('10:15', 'Input harga Daging Ayam', 7, 1),
('09:58', 'Publikasi data harga', 2, null),
('09:50', 'Tambah pedagang baru', 1, 4),
('09:12', 'Generate laporan bulanan', 2, null),
('08:45', 'Login sistem', 1, null);

-- Ketersediaan (Sample Data)
INSERT INTO ketersediaan (komoditas_id, pasar_id, ketersediaan, status) 
SELECT id, 1, 95, 'Tersedia' FROM komoditas WHERE id <= 8;